/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Badge {
  'id' : string,
  'unlockedAt' : [] | [Timestamp],
  'name' : string,
  'description' : string,
  'iconKey' : string,
}
export interface Collection {
  'id' : Id,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
}
export interface CollectionInput { 'name' : string, 'description' : string }
export interface CollectionStats {
  'collectionId' : Id,
  'averageAccuracy' : number,
  'totalItems' : bigint,
  'retentionRate' : number,
}
export interface DailyActivity {
  'dateKey' : DateKey,
  'correctCount' : bigint,
  'reviewCount' : bigint,
}
export interface DashboardStats {
  'itemsDueToday' : bigint,
  'studyStreak' : bigint,
  'totalItems' : bigint,
  'accuracyPercent' : number,
}
export type DateKey = bigint;
export type Difficulty = { 'new' : null } |
  { 'review' : null } |
  { 'relearning' : null } |
  { 'learning' : null };
export interface FsrsState {
  'difficulty' : number,
  'stability' : number,
  'retrievability' : number,
}
export type Id = bigint;
export interface ItemFilter {
  'collectionId' : [] | [Id],
  'tags' : Array<string>,
  'dueBefore' : [] | [DateKey],
}
export interface MemoryItem {
  'id' : Id,
  'question' : string,
  'collectionId' : Id,
  'fsrs' : FsrsState,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'answer' : string,
  'updatedAt' : Timestamp,
  'state' : Difficulty,
  'nextReviewDate' : DateKey,
}
export interface MemoryItemInput {
  'question' : string,
  'collectionId' : Id,
  'tags' : Array<string>,
  'answer' : string,
}
export interface MemoryItemUpdate {
  'question' : string,
  'tags' : Array<string>,
  'answer' : string,
}
export type Rating = bigint;
export interface ReviewEvent {
  'id' : Id,
  'itemId' : Id,
  'collectionId' : Id,
  'reviewedAt' : Timestamp,
  'rating' : Rating,
}
export type Timestamp = bigint;
export interface UserProgress {
  'totalXp' : bigint,
  'badges' : Array<Badge>,
  'lastUpdated' : Timestamp,
  'level' : bigint,
}
export interface XpEvent {
  'id' : Id,
  'userId' : Principal,
  'earnedAt' : Timestamp,
  'amount' : bigint,
  'reason' : string,
}
export interface _SERVICE {
  'awardXpForReview' : ActorMethod<[Rating], UserProgress>,
  'createCollection' : ActorMethod<[CollectionInput], Collection>,
  'createItem' : ActorMethod<[MemoryItemInput], MemoryItem>,
  'deleteCollection' : ActorMethod<[Id], boolean>,
  'deleteItem' : ActorMethod<[Id], boolean>,
  'getCollection' : ActorMethod<[Id], [] | [Collection]>,
  'getCollectionStats' : ActorMethod<[Id], [] | [CollectionStats]>,
  'getDailyActivity' : ActorMethod<[], Array<DailyActivity>>,
  'getDashboardStats' : ActorMethod<[DateKey], DashboardStats>,
  'getDueItems' : ActorMethod<[DateKey], Array<MemoryItem>>,
  'getItem' : ActorMethod<[Id], [] | [MemoryItem]>,
  'getProgress' : ActorMethod<[], [] | [UserProgress]>,
  'listBadges' : ActorMethod<[], Array<Badge>>,
  'listCollections' : ActorMethod<[], Array<Collection>>,
  'listItems' : ActorMethod<[ItemFilter], Array<MemoryItem>>,
  'listReviewEvents' : ActorMethod<[], Array<ReviewEvent>>,
  'listXpEvents' : ActorMethod<[], Array<XpEvent>>,
  'submitReview' : ActorMethod<[Id, Rating], [] | [ReviewEvent]>,
  'updateCollection' : ActorMethod<[Id, CollectionInput], [] | [Collection]>,
  'updateItem' : ActorMethod<[Id, MemoryItemUpdate], [] | [MemoryItem]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];