/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CollectionInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Id = IDL.Nat;
export const Timestamp = IDL.Int;
export const Collection = IDL.Record({
  'id' : Id,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
});
export const MemoryItemInput = IDL.Record({
  'question' : IDL.Text,
  'collectionId' : Id,
  'tags' : IDL.Vec(IDL.Text),
  'answer' : IDL.Text,
});
export const FsrsState = IDL.Record({
  'difficulty' : IDL.Float64,
  'stability' : IDL.Float64,
  'retrievability' : IDL.Float64,
});
export const Difficulty = IDL.Variant({
  'new' : IDL.Null,
  'review' : IDL.Null,
  'relearning' : IDL.Null,
  'learning' : IDL.Null,
});
export const DateKey = IDL.Nat;
export const MemoryItem = IDL.Record({
  'id' : Id,
  'question' : IDL.Text,
  'collectionId' : Id,
  'fsrs' : FsrsState,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'answer' : IDL.Text,
  'updatedAt' : Timestamp,
  'state' : Difficulty,
  'nextReviewDate' : DateKey,
});
export const CollectionStats = IDL.Record({
  'collectionId' : Id,
  'averageAccuracy' : IDL.Float64,
  'totalItems' : IDL.Nat,
  'retentionRate' : IDL.Float64,
});
export const DailyActivity = IDL.Record({
  'dateKey' : DateKey,
  'correctCount' : IDL.Nat,
  'reviewCount' : IDL.Nat,
});
export const DashboardStats = IDL.Record({
  'itemsDueToday' : IDL.Nat,
  'studyStreak' : IDL.Nat,
  'totalItems' : IDL.Nat,
  'accuracyPercent' : IDL.Float64,
});
export const ItemFilter = IDL.Record({
  'collectionId' : IDL.Opt(Id),
  'tags' : IDL.Vec(IDL.Text),
  'dueBefore' : IDL.Opt(DateKey),
});
export const Rating = IDL.Nat;
export const ReviewEvent = IDL.Record({
  'id' : Id,
  'itemId' : Id,
  'collectionId' : Id,
  'reviewedAt' : Timestamp,
  'rating' : Rating,
});
export const MemoryItemUpdate = IDL.Record({
  'question' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'answer' : IDL.Text,
});

export const idlService = IDL.Service({
  'createCollection' : IDL.Func([CollectionInput], [Collection], []),
  'createItem' : IDL.Func([MemoryItemInput], [MemoryItem], []),
  'deleteCollection' : IDL.Func([Id], [IDL.Bool], []),
  'deleteItem' : IDL.Func([Id], [IDL.Bool], []),
  'getCollection' : IDL.Func([Id], [IDL.Opt(Collection)], ['query']),
  'getCollectionStats' : IDL.Func([Id], [IDL.Opt(CollectionStats)], ['query']),
  'getDailyActivity' : IDL.Func([], [IDL.Vec(DailyActivity)], ['query']),
  'getDashboardStats' : IDL.Func([DateKey], [DashboardStats], ['query']),
  'getDueItems' : IDL.Func([DateKey], [IDL.Vec(MemoryItem)], ['query']),
  'getItem' : IDL.Func([Id], [IDL.Opt(MemoryItem)], ['query']),
  'listCollections' : IDL.Func([], [IDL.Vec(Collection)], ['query']),
  'listItems' : IDL.Func([ItemFilter], [IDL.Vec(MemoryItem)], ['query']),
  'listReviewEvents' : IDL.Func([], [IDL.Vec(ReviewEvent)], ['query']),
  'submitReview' : IDL.Func([Id, Rating], [IDL.Opt(ReviewEvent)], []),
  'updateCollection' : IDL.Func(
      [Id, CollectionInput],
      [IDL.Opt(Collection)],
      [],
    ),
  'updateItem' : IDL.Func([Id, MemoryItemUpdate], [IDL.Opt(MemoryItem)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CollectionInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Id = IDL.Nat;
  const Timestamp = IDL.Int;
  const Collection = IDL.Record({
    'id' : Id,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
  });
  const MemoryItemInput = IDL.Record({
    'question' : IDL.Text,
    'collectionId' : Id,
    'tags' : IDL.Vec(IDL.Text),
    'answer' : IDL.Text,
  });
  const FsrsState = IDL.Record({
    'difficulty' : IDL.Float64,
    'stability' : IDL.Float64,
    'retrievability' : IDL.Float64,
  });
  const Difficulty = IDL.Variant({
    'new' : IDL.Null,
    'review' : IDL.Null,
    'relearning' : IDL.Null,
    'learning' : IDL.Null,
  });
  const DateKey = IDL.Nat;
  const MemoryItem = IDL.Record({
    'id' : Id,
    'question' : IDL.Text,
    'collectionId' : Id,
    'fsrs' : FsrsState,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'answer' : IDL.Text,
    'updatedAt' : Timestamp,
    'state' : Difficulty,
    'nextReviewDate' : DateKey,
  });
  const CollectionStats = IDL.Record({
    'collectionId' : Id,
    'averageAccuracy' : IDL.Float64,
    'totalItems' : IDL.Nat,
    'retentionRate' : IDL.Float64,
  });
  const DailyActivity = IDL.Record({
    'dateKey' : DateKey,
    'correctCount' : IDL.Nat,
    'reviewCount' : IDL.Nat,
  });
  const DashboardStats = IDL.Record({
    'itemsDueToday' : IDL.Nat,
    'studyStreak' : IDL.Nat,
    'totalItems' : IDL.Nat,
    'accuracyPercent' : IDL.Float64,
  });
  const ItemFilter = IDL.Record({
    'collectionId' : IDL.Opt(Id),
    'tags' : IDL.Vec(IDL.Text),
    'dueBefore' : IDL.Opt(DateKey),
  });
  const Rating = IDL.Nat;
  const ReviewEvent = IDL.Record({
    'id' : Id,
    'itemId' : Id,
    'collectionId' : Id,
    'reviewedAt' : Timestamp,
    'rating' : Rating,
  });
  const MemoryItemUpdate = IDL.Record({
    'question' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'answer' : IDL.Text,
  });
  
  return IDL.Service({
    'createCollection' : IDL.Func([CollectionInput], [Collection], []),
    'createItem' : IDL.Func([MemoryItemInput], [MemoryItem], []),
    'deleteCollection' : IDL.Func([Id], [IDL.Bool], []),
    'deleteItem' : IDL.Func([Id], [IDL.Bool], []),
    'getCollection' : IDL.Func([Id], [IDL.Opt(Collection)], ['query']),
    'getCollectionStats' : IDL.Func(
        [Id],
        [IDL.Opt(CollectionStats)],
        ['query'],
      ),
    'getDailyActivity' : IDL.Func([], [IDL.Vec(DailyActivity)], ['query']),
    'getDashboardStats' : IDL.Func([DateKey], [DashboardStats], ['query']),
    'getDueItems' : IDL.Func([DateKey], [IDL.Vec(MemoryItem)], ['query']),
    'getItem' : IDL.Func([Id], [IDL.Opt(MemoryItem)], ['query']),
    'listCollections' : IDL.Func([], [IDL.Vec(Collection)], ['query']),
    'listItems' : IDL.Func([ItemFilter], [IDL.Vec(MemoryItem)], ['query']),
    'listReviewEvents' : IDL.Func([], [IDL.Vec(ReviewEvent)], ['query']),
    'submitReview' : IDL.Func([Id, Rating], [IDL.Opt(ReviewEvent)], []),
    'updateCollection' : IDL.Func(
        [Id, CollectionInput],
        [IDL.Opt(Collection)],
        [],
      ),
    'updateItem' : IDL.Func([Id, MemoryItemUpdate], [IDL.Opt(MemoryItem)], []),
  });
};

export const init = ({ IDL }) => { return []; };