/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type Rating = bigint;
export interface FsrsState {
    difficulty: number;
    stability: number;
    retrievability: number;
}
export type DateKey = bigint;
export interface ReviewEvent {
    id: Id;
    itemId: Id;
    collectionId: Id;
    reviewedAt: Timestamp;
    rating: Rating;
}
export interface ItemFilter {
    collectionId?: Id;
    tags: Array<string>;
    dueBefore?: DateKey;
}
export interface DashboardStats {
    itemsDueToday: bigint;
    studyStreak: bigint;
    totalItems: bigint;
    accuracyPercent: number;
}
export interface UserProgress {
    totalXp: bigint;
    badges: Array<Badge>;
    lastUpdated: Timestamp;
    level: bigint;
}
export interface MemoryItemInput {
    question: string;
    collectionId: Id;
    tags: Array<string>;
    answer: string;
}
export interface Badge {
    id: string;
    unlockedAt?: Timestamp;
    name: string;
    description: string;
    iconKey: string;
}
export interface Collection {
    id: Id;
    name: string;
    createdAt: Timestamp;
    description: string;
}
export interface MemoryItem {
    id: Id;
    question: string;
    collectionId: Id;
    fsrs: FsrsState;
    createdAt: Timestamp;
    tags: Array<string>;
    answer: string;
    updatedAt: Timestamp;
    state: Difficulty;
    nextReviewDate: DateKey;
}
export interface MemoryItemUpdate {
    question: string;
    tags: Array<string>;
    answer: string;
}
export type Id = bigint;
export interface DailyActivity {
    dateKey: DateKey;
    correctCount: bigint;
    reviewCount: bigint;
}
export interface CollectionStats {
    collectionId: Id;
    averageAccuracy: number;
    totalItems: bigint;
    retentionRate: number;
}
export interface XpEvent {
    id: Id;
    userId: Principal;
    earnedAt: Timestamp;
    amount: bigint;
    reason: string;
}
export interface CollectionInput {
    name: string;
    description: string;
}
export enum Difficulty {
    new_ = "new",
    review = "review",
    relearning = "relearning",
    learning = "learning"
}
export interface backendInterface {
    awardXpForReview(rating: Rating): Promise<UserProgress>;
    createCollection(input: CollectionInput): Promise<Collection>;
    createItem(input: MemoryItemInput): Promise<MemoryItem>;
    deleteCollection(id: Id): Promise<boolean>;
    deleteItem(id: Id): Promise<boolean>;
    getCollection(id: Id): Promise<Collection | null>;
    getCollectionStats(id: Id): Promise<CollectionStats | null>;
    getDailyActivity(): Promise<Array<DailyActivity>>;
    getDashboardStats(todayKey: DateKey): Promise<DashboardStats>;
    getDueItems(todayKey: DateKey): Promise<Array<MemoryItem>>;
    getItem(id: Id): Promise<MemoryItem | null>;
    getProgress(): Promise<UserProgress | null>;
    listBadges(): Promise<Array<Badge>>;
    listCollections(): Promise<Array<Collection>>;
    listItems(filter: ItemFilter): Promise<Array<MemoryItem>>;
    listReviewEvents(): Promise<Array<ReviewEvent>>;
    listXpEvents(): Promise<Array<XpEvent>>;
    submitReview(itemId: Id, rating: Rating): Promise<ReviewEvent | null>;
    updateCollection(id: Id, input: CollectionInput): Promise<Collection | null>;
    updateItem(id: Id, input: MemoryItemUpdate): Promise<MemoryItem | null>;
}
import type { Badge as _Badge, Collection as _Collection, CollectionStats as _CollectionStats, DateKey as _DateKey, Difficulty as _Difficulty, FsrsState as _FsrsState, Id as _Id, ItemFilter as _ItemFilter, MemoryItem as _MemoryItem, ReviewEvent as _ReviewEvent, Timestamp as _Timestamp, UserProgress as _UserProgress } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async awardXpForReview(arg0: Rating): Promise<UserProgress> {
        if (this.processError) {
            try {
                const result = await this.actor.awardXpForReview(arg0);
                return from_candid_UserProgress_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.awardXpForReview(arg0);
            return from_candid_UserProgress_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCollection(arg0: CollectionInput): Promise<Collection> {
        if (this.processError) {
            try {
                const result = await this.actor.createCollection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCollection(arg0);
            return result;
        }
    }
    async createItem(arg0: MemoryItemInput): Promise<MemoryItem> {
        if (this.processError) {
            try {
                const result = await this.actor.createItem(arg0);
                return from_candid_MemoryItem_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createItem(arg0);
            return from_candid_MemoryItem_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCollection(arg0: Id): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCollection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCollection(arg0);
            return result;
        }
    }
    async deleteItem(arg0: Id): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteItem(arg0);
            return result;
        }
    }
    async getCollection(arg0: Id): Promise<Collection | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollection(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollection(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCollectionStats(arg0: Id): Promise<CollectionStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollectionStats(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollectionStats(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyActivity(): Promise<Array<DailyActivity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyActivity();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyActivity();
            return result;
        }
    }
    async getDashboardStats(arg0: DateKey): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats(arg0);
            return result;
        }
    }
    async getDueItems(arg0: DateKey): Promise<Array<MemoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDueItems(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDueItems(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getItem(arg0: Id): Promise<MemoryItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getItem(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItem(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgress(): Promise<UserProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgress();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgress();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async listBadges(): Promise<Array<Badge>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBadges();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBadges();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCollections(): Promise<Array<Collection>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCollections();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCollections();
            return result;
        }
    }
    async listItems(arg0: ItemFilter): Promise<Array<MemoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listItems(to_candid_ItemFilter_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listItems(to_candid_ItemFilter_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async listReviewEvents(): Promise<Array<ReviewEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.listReviewEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listReviewEvents();
            return result;
        }
    }
    async listXpEvents(): Promise<Array<XpEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.listXpEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listXpEvents();
            return result;
        }
    }
    async submitReview(arg0: Id, arg1: Rating): Promise<ReviewEvent | null> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0, arg1);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0, arg1);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCollection(arg0: Id, arg1: CollectionInput): Promise<Collection | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCollection(arg0, arg1);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCollection(arg0, arg1);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateItem(arg0: Id, arg1: MemoryItemUpdate): Promise<MemoryItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateItem(arg0, arg1);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateItem(arg0, arg1);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Badge_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Badge): Badge {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Difficulty_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_MemoryItem_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemoryItem): MemoryItem {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserProgress_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProgress): UserProgress {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Collection]): Collection | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CollectionStats]): CollectionStats | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MemoryItem]): MemoryItem | null {
    return value.length === 0 ? null : from_candid_MemoryItem_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProgress]): UserProgress | null {
    return value.length === 0 ? null : from_candid_UserProgress_n1(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReviewEvent]): ReviewEvent | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalXp: bigint;
    badges: Array<_Badge>;
    lastUpdated: _Timestamp;
    level: bigint;
}): {
    totalXp: bigint;
    badges: Array<Badge>;
    lastUpdated: Timestamp;
    level: bigint;
} {
    return {
        totalXp: value.totalXp,
        badges: from_candid_vec_n3(_uploadFile, _downloadFile, value.badges),
        lastUpdated: value.lastUpdated,
        level: value.level
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    unlockedAt: [] | [_Timestamp];
    name: string;
    description: string;
    iconKey: string;
}): {
    id: string;
    unlockedAt?: Timestamp;
    name: string;
    description: string;
    iconKey: string;
} {
    return {
        id: value.id,
        unlockedAt: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.unlockedAt)),
        name: value.name,
        description: value.description,
        iconKey: value.iconKey
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    question: string;
    collectionId: _Id;
    fsrs: _FsrsState;
    createdAt: _Timestamp;
    tags: Array<string>;
    answer: string;
    updatedAt: _Timestamp;
    state: _Difficulty;
    nextReviewDate: _DateKey;
}): {
    id: Id;
    question: string;
    collectionId: Id;
    fsrs: FsrsState;
    createdAt: Timestamp;
    tags: Array<string>;
    answer: string;
    updatedAt: Timestamp;
    state: Difficulty;
    nextReviewDate: DateKey;
} {
    return {
        id: value.id,
        question: value.question,
        collectionId: value.collectionId,
        fsrs: value.fsrs,
        createdAt: value.createdAt,
        tags: value.tags,
        answer: value.answer,
        updatedAt: value.updatedAt,
        state: from_candid_Difficulty_n9(_uploadFile, _downloadFile, value.state),
        nextReviewDate: value.nextReviewDate
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    review: null;
} | {
    relearning: null;
} | {
    learning: null;
}): Difficulty {
    return "new" in value ? Difficulty.new : "review" in value ? Difficulty.review : "relearning" in value ? Difficulty.relearning : "learning" in value ? Difficulty.learning : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MemoryItem>): Array<MemoryItem> {
    return value.map((x)=>from_candid_MemoryItem_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Badge>): Array<Badge> {
    return value.map((x)=>from_candid_Badge_n4(_uploadFile, _downloadFile, x));
}
function to_candid_ItemFilter_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemFilter): _ItemFilter {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    collectionId?: Id;
    tags: Array<string>;
    dueBefore?: DateKey;
}): {
    collectionId: [] | [_Id];
    tags: Array<string>;
    dueBefore: [] | [_DateKey];
} {
    return {
        collectionId: value.collectionId ? candid_some(value.collectionId) : candid_none(),
        tags: value.tags,
        dueBefore: value.dueBefore ? candid_some(value.dueBefore) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
